"""add is_global to meeting space

Revision ID: 03143aab1448
Revises: e87485e6043e
Create Date: 2026-08-02 06:02:30.524495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03143aab1448'
down_revision: Union[str, Sequence[str], None] = 'e87485e6043e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_spaces', sa.Column('is_global', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_spaces', 'is_global')
    # ### end Alembic commands ###
