"""soft_delete_chat_sessions

Revision ID: 1d4d1b6db1d5
Revises: f3e234660eef
Create Date: 2026-08-06 07:43:02.903037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4d1b6db1d5'
down_revision: Union[str, Sequence[str], None] = 'f3e234660eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
