"""Add meeting enrichments table

Revision ID: 4213aadd92ae
Revises: 9cbf8cd71edc
Create Date: 2026-07-28 07:56:13.396083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4213aadd92ae'
down_revision: Union[str, Sequence[str], None] = '9cbf8cd71edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
