"""Add meeting processing status table

Revision ID: 4d265262000c
Revises: da4acb1cb17e
Create Date: 2026-07-28 10:35:45.993261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d265262000c'
down_revision: Union[str, Sequence[str], None] = 'da4acb1cb17e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_processing_status',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('transcript_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='pipeline_status_enum'), nullable=False),
    sa.Column('knowledge_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='pipeline_status_enum'), nullable=False),
    sa.Column('enrichment_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='pipeline_status_enum'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_processing_status')
    # ### end Alembic commands ###
