"""make artifacts project aware

Revision ID: e87485e6043e
Revises: 376bb4d299a2
Create Date: 2026-08-02 05:40:37.289702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e87485e6043e'
down_revision: Union[str, Sequence[str], None] = '376bb4d299a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_action_items', sa.Column('project_id', sa.Integer(), nullable=True))
    op.alter_column('meeting_action_items', 'meeting_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'meeting_action_items', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('meeting_concerns', sa.Column('project_id', sa.Integer(), nullable=True))
    op.alter_column('meeting_concerns', 'meeting_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'meeting_concerns', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('meeting_decisions', sa.Column('project_id', sa.Integer(), nullable=True))
    op.alter_column('meeting_decisions', 'meeting_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'meeting_decisions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('meeting_requirements', sa.Column('project_id', sa.Integer(), nullable=True))
    op.alter_column('meeting_requirements', 'meeting_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'meeting_requirements', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('meeting_summaries', sa.Column('project_id', sa.Integer(), nullable=True))
    op.alter_column('meeting_summaries', 'meeting_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'meeting_summaries', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('meeting_topics', sa.Column('project_id', sa.Integer(), nullable=True))
    op.alter_column('meeting_topics', 'meeting_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'meeting_topics', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meeting_topics', type_='foreignkey')
    op.alter_column('meeting_topics', 'meeting_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('meeting_topics', 'project_id')
    op.drop_constraint(None, 'meeting_summaries', type_='foreignkey')
    op.alter_column('meeting_summaries', 'meeting_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('meeting_summaries', 'project_id')
    op.drop_constraint(None, 'meeting_requirements', type_='foreignkey')
    op.alter_column('meeting_requirements', 'meeting_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('meeting_requirements', 'project_id')
    op.drop_constraint(None, 'meeting_decisions', type_='foreignkey')
    op.alter_column('meeting_decisions', 'meeting_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('meeting_decisions', 'project_id')
    op.drop_constraint(None, 'meeting_concerns', type_='foreignkey')
    op.alter_column('meeting_concerns', 'meeting_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('meeting_concerns', 'project_id')
    op.drop_constraint(None, 'meeting_action_items', type_='foreignkey')
    op.alter_column('meeting_action_items', 'meeting_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('meeting_action_items', 'project_id')
    # ### end Alembic commands ###
