"""knowledge_chunk_project_id

Revision ID: f3e234660eef
Revises: 3c667171cf5c
Create Date: 2026-08-04 13:04:55.220206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e234660eef'
down_revision: Union[str, Sequence[str], None] = '3c667171cf5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable=True
    op.add_column('knowledge_chunks', sa.Column('project_id', sa.Integer(), nullable=True))
    
    # 2. Backfill project_id
    op.execute("""
        UPDATE knowledge_chunks kc
        SET project_id = ms.project_id
        FROM meetings m
        JOIN meeting_spaces ms ON m.meeting_space_id = ms.id
        WHERE kc.meeting_id = m.id
    """)
    
    # 3. Alter project_id to nullable=False
    op.alter_column('knowledge_chunks', 'project_id', nullable=False)

    # 4. Alter meeting_id to nullable=True
    op.alter_column('knowledge_chunks', 'meeting_id',
               existing_type=sa.UUID(),
               nullable=True)
               
    # 5. Drop old FK and add new ones
    op.drop_constraint('knowledge_chunks_meeting_id_fkey', 'knowledge_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_chunks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'knowledge_chunks', 'meetings', ['meeting_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_chunks', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_chunks_meeting_id_fkey'), 'knowledge_chunks', 'meetings', ['meeting_id'], ['id'], ondelete='CASCADE')
    op.alter_column('knowledge_chunks', 'meeting_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('knowledge_chunks', 'project_id')
    # ### end Alembic commands ###
